on: [push]

jobs:
  example_job:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    name: A job to show example
    steps:
      - name: CSPDriver step
        id: example
        uses: qensus-labs/venafi-codesigning-wrapper-action@v1.0
        with:
          #csc-url: 'https://uvo1gm6lvzt1xsk5n8l.env.cloudshare.com/csc'
          csc-url: 'https://uvo1gm8xtvysk75eax6.env.cloudshare.com/csc'
      # Use the output from the `hello` step
      - name: SHow CSPDriver version
        run: pkcs11config --version