on:
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ["self-hosted", "Windows", "X64" ]
    name: Example with self-hosted Windows runner
    steps:
      - name: Setup CSPDriver
        id: cspdriver
        uses: qensus-labs/venafi-codesigning-wrapper-action@v1.0.0
        with:
          tpp-csc-url: 'https://uvo1gm8xtvysk75eax6.env.cloudshare.com/csc'
          tpp-auth-url: 'https://uvo1gm8xtvysk75eax6.env.cloudshare.com/vedauth'
          tpp-hsm-url: 'https://uvo1gm8xtvysk75eax6.env.cloudshare.com/vedhsm'
          include-config: 'true'
      - name: Display output values
        run: |
          echo "Output \"csp-driver-cached-config\" [${{steps.cspdriver.outputs.csp-driver-cached-config}}]"
          echo "Output \"csp-driver-cached-path\" [${{steps.cspdriver.outputs.csp-driver-cached-path}}]"
          echo "Output \"csp-driver-cached-version\" [${{steps.cspdriver.outputs.csp-driver-cached-version}}]"
      - name: Check CSPDriver (version)
        run: cspconfig.exe version
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Venafi Python package
        run: pip install venafi-csp
      - name: Run Library command
        shell: cmd
        run: python -mvenafi_csp.version_command
      - name: Install SignTool package
        run: |
          $ErrorActionPreference = 'Stop'; `
          Set-PSDebug -Trace 1

          Invoke-WebRequest -UseBasicParsing -Out \winsdksetup.exe`
            https://download.microsoft.com/download/1/c/3/1c3d5161-d9e9-4e4b-9b43-b70fe8be268c/windowssdk/winsdksetup.exe

          $proc = Start-Process -Wait -NoNewWindow -PassThru \winsdksetup.exe `
            -ArgumentList ('/Features','OptionId.SigningTools','/Quiet','/NoRestart','/Log','\winsdksetup.log')

          if ($proc.ExitCode -ne 0) {
            Get-Content \winsdksetup.log
            exit 1
          }

          New-Item -ItemType SymbolicLink -Path \winsdk `
            -Target "${env:ProgramFiles(x86)}\Windows` Kits\10\bin\10.0.19041.0"
          setx /M PATH "${env:PATH};C:\winsdk\x64"
          
          Remove-Item -Force \winsdksetup*